name: Windows RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Create User
        run: |
          net user runneradmin Password@123 /add
          net localgroup administrators runneradmin /add

      - name: Show Connection Info
        run: |
          echo "RDP is enabled on this machine."
          echo "Username: runneradmin"
          echo "Password: Password@123"
          ipconfig
          Start-Sleep -Seconds 21600
